// Single source of truth for all editable site content.
// Neutral placeholders — the owner fills these in via the admin panel (#/admin).
export const CONTENT_VERSION = 1;

export const defaultContent = {
  settings: {
    brandName: "Your",
    brandAccent: "Name",
    theme: {
      bg: "#080808",
      bg2: "#101010",
      text: "#ffffff",
      accent: "#ea580c",
      accent2: "#f59e0b",
      fontDisplay: "Poppins",
      fontBody: "Poppins",
    },
    globe: true,
    customCss: "",
  },
  nav: [
    { label: "Home", href: "#home" },
    { label: "About", href: "#about" },
    { label: "Services", href: "#services" },
    { label: "Skills", href: "#skills" },
    { label: "Work", href: "#portfolio" },
    { label: "Contact", href: "#contact" },
  ],
  hero: {
    enabled: true,
    greeting: "Hello, It's Me",
    name: "Your Name",
    intro: "And I'm a",
    roles: ["Web Developer", "UI Designer", "Freelancer"],
    bio: "A short, punchy introduction about yourself. Tell visitors who you are and what you build. Every word here is editable from the admin panel.",
    photo: "",
    ctaLabel: "Hire Me",
    ctaHref: "#contact",
    secondaryLabel: "Download CV",
    secondaryHref: "#",
    socials: [
      { icon: "bx bxl-linkedin", href: "#" },
      { icon: "bx bxl-github", href: "#" },
      { icon: "bx bxl-instagram", href: "#" },
      { icon: "bx bxl-twitter", href: "#" },
    ],
  },
  about: {
    enabled: true,
    heading: "About",
    headingAccent: "Me",
    photo: "",
    title: "Frontend Developer!",
    subtitle: "Your role / tagline",
    body: "Replace this with a longer story about your background, your skills, and what you love building.\n\nUse blank lines to separate paragraphs. Everything here is editable from the admin panel.",
    stats: [
      { value: "3+", label: "Years Experience" },
      { value: "40+", label: "Projects Done" },
      { value: "20+", label: "Happy Clients" },
    ],
    ctaLabel: "Read More",
    ctaHref: "#",
  },
  services: {
    enabled: true,
    heading: "My",
    headingAccent: "Services",
    subheading: "What I can do for you",
    items: [
      { icon: "bx bx-code-alt", title: "Web Development", desc: "Describe this service — what you offer and why clients should pick you." },
      { icon: "bx bx-palette", title: "UI / UX Design", desc: "Describe this service — what you offer and why clients should pick you." },
      { icon: "bx bx-mobile-alt", title: "App Design", desc: "Describe this service — what you offer and why clients should pick you." },
    ],
  },
  skills: {
    enabled: true,
    heading: "My",
    headingAccent: "Skills",
    subheading: "Technologies I work with",
    items: [
      { name: "HTML & CSS", level: 90 },
      { name: "JavaScript", level: 80 },
      { name: "React", level: 72 },
      { name: "UI Design", level: 85 },
    ],
  },
  portfolio: {
    enabled: true,
    heading: "Latest",
    headingAccent: "Projects",
    subheading: "A selection of my recent work",
    items: [
      { image: "", title: "Project One", desc: "Short project description.", href: "#", tag: "Web" },
      { image: "", title: "Project Two", desc: "Short project description.", href: "#", tag: "Design" },
      { image: "", title: "Project Three", desc: "Short project description.", href: "#", tag: "App" },
      { image: "", title: "Project Four", desc: "Short project description.", href: "#", tag: "Web" },
      { image: "", title: "Project Five", desc: "Short project description.", href: "#", tag: "Brand" },
      { image: "", title: "Project Six", desc: "Short project description.", href: "#", tag: "Web" },
    ],
  },
  contact: {
    enabled: true,
    heading: "Contact",
    headingAccent: "Me",
    subheading: "Let's work together",
    email: "you@example.com",
    phone: "+60 12 345 6789",
    location: "Kuala Lumpur, Malaysia",
    formEnabled: true,
    formAction: "",
  },
  footer: {
    text: "© 2026 Your Name. All rights reserved.",
    socials: [
      { icon: "bx bxl-linkedin", href: "#" },
      { icon: "bx bxl-github", href: "#" },
      { icon: "bx bxl-instagram", href: "#" },
    ],
  },
};
